TRUNCATE offers RESTART IDENTITY CASCADE;
/* Ingresando Ofertas */
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('2 Zapatillas + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Canillera',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Zapatilla + Pelota',99,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Combo 1 Lotto',119,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Combo 2 Lotto',109,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Combo 3 Lotto',109,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Combo 4 Lotto',109,1);
INSERT INTO offers (description,price,campaign_id) VALUES ('Combo 5 Lotto',109,1);
