#!/usr/bin/env php
<?php
    define('BASEPATH', TRUE);

    require('application/config/database.php');

    $host = $db['default']['hostname'];
    $port = 5432;
    $dbname = $db['default']['database'];
    $user = $db['default']['username'];
    $password = $db['default']['password'];
    $connection = "host=$host port=$port dbname=$dbname user=$user password=$password";
    $pg = pg_connect($connection) or die('Connection error: ' . pg_last_error());

    if (count($argv) === 1) {
        $query = pg_query($pg, "SELECT text_value FROM settings WHERE description = 'last_file_migrated'") or die ('Error in query');
        $last_file = '';
        $include_file = FALSE;

        if (pg_num_rows($query) > 0) {
            while ($row = pg_fetch_array($query)) {
                $last_file = $row['text_value'];
            }
        }

        if (strlen($last_file) > 0) {
            $files = array_filter(scandir('database', 0), function ($file) use ($last_file, &$include_file) {
                $filter = (strpos($file, 'queries ') === 0 AND substr($file, -4) === '.sql' AND $include_file);

                if ($file === $last_file) {
                    $include_file = TRUE;
                }

                return $filter;
            });

            if (count($files) > 0) {
                foreach ($files as $file) {
                    echo $file . ": ";

                    $sql = trim(file_get_contents("database/$file"), " \t\n\r\0\x0B\xEF\xBB\xBF");
                    $query = pg_query($pg, $sql);

                    if (!$query) {
                        echo pg_last_error($pg);
                    } else {
                        echo 'executed successfully';
                    }

                    echo "\n";

                    $last_file = $file;
                }

                pg_query($pg, "UPDATE settings SET text_value = '$last_file' WHERE description = 'last_file_migrated'") or die ('Error when updating last file migrated');
            } else {
                echo "Message: database is updated (up to \"$last_file\")\n";
            }
        } else {
            echo "Error: last file migrated was not found\n";
        }
    } elseif (count($argv) === 2 && $argv[1] === 'fix') {
        $files = array_filter(scandir('database', 0), function ($file) {
            return (strpos($file, 'queries ') === 0 AND substr($file, -4) === '.sql');
        });

        if (count($files) > 0) {
            $last_file = end($files);

            pg_query($pg, "UPDATE settings SET text_value = '$last_file' WHERE description = 'last_file_migrated'") or die ('Error when updating last file migrated');

            echo "Message: head up to \"$last_file\"\n";
        } else {
            echo "Error: no file found\n";
        }
    }
?>
