/* Marcas */
INSERT INTO brands (description) VALUES ('LOTTO');
INSERT INTO brands (description) VALUES ('REEBOK');
INSERT INTO brands (description) VALUES ('ADIDAS');
INSERT INTO brands (description) VALUES ('ONITSUKA');
INSERT INTO brands (description) VALUES ('ASICS');
INSERT INTO brands (description) VALUES ('SKECHERS');
INSERT INTO brands (description) VALUES ('BEN 10');
INSERT INTO brands (description) VALUES ('HOT WHEELS');
INSERT INTO brands (description) VALUES ('NIKE');
INSERT INTO brands (description) VALUES ('CARTAGO');
INSERT INTO brands (description) VALUES ('GRENDHA');
INSERT INTO brands (description) VALUES ('IPANEMA');
INSERT INTO brands (description) VALUES ('RIDER');
INSERT INTO brands (description) VALUES ('HELLO KITTY');
INSERT INTO brands (description) VALUES ('GUGA');
INSERT INTO brands (description) VALUES ('CONVERSE');
INSERT INTO brands (description) VALUES ('KARL-KANI');
INSERT INTO brands (description) VALUES ('VANS');
INSERT INTO brands (description) VALUES ('TOP SAIDER');
INSERT INTO brands (description) VALUES ('KAPPA');
INSERT INTO brands (description) VALUES ('SPIDER-MAN');
INSERT INTO brands (description) VALUES ('NOCAUT');
INSERT INTO brands (description) VALUES ('MONSTER HIGH');
INSERT INTO brands (description) VALUES ('BADBOY');
INSERT INTO brands (description) VALUES ('LFA');
INSERT INTO brands (description) VALUES ('SPALDING');
INSERT INTO brands (description) VALUES ('DOITE');
INSERT INTO brands (description) VALUES ('PRINCE');
INSERT INTO brands (description) VALUES ('FILA');
INSERT INTO brands (description) VALUES ('MEDIUM');
INSERT INTO brands (description) VALUES ('NEW BALANCE');
INSERT INTO brands (description) VALUES ('PUMA');
INSERT INTO brands (description) VALUES ('UMBRO');
INSERT INTO brands (description) VALUES ('PAHT FARM');
INSERT INTO brands (description) VALUES ('TIMBERLAND');
INSERT INTO brands (description) VALUES ('KEDS');
INSERT INTO brands (description) VALUES ('ATHLETIC');
INSERT INTO brands (description) VALUES ('WARRIOR');
INSERT INTO brands (description) VALUES ('LIFESTYLE');
INSERT INTO brands (description) VALUES ('WILSON');
