INSERT INTO credit_card_types (description, abbrev) VALUES ('VISA', 'VIS');
INSERT INTO credit_card_types (description, abbrev) VALUES ('AMERICAN EXPRESS', 'AEX');
INSERT INTO credit_card_types (description, abbrev) VALUES ('DINERS', 'DIN');
INSERT INTO credit_card_types (description, abbrev) VALUES ('VISA ELECTRON', 'VEL');
INSERT INTO credit_card_types (description, abbrev) VALUES ('MASTERCARD', 'MTC');
INSERT INTO credit_card_types (description, abbrev) VALUES ('MAESTRO', 'MAE');
INSERT INTO credit_card_types (description, abbrev) VALUES ('NETCARD', 'NET');
INSERT INTO credit_card_types (description, abbrev) VALUES ('CARSA CARD', 'CAR');
INSERT INTO credit_card_types (description, abbrev) VALUES ('CURACAO CARD', 'CUR');
INSERT INTO credit_card_types (description, abbrev) VALUES ('CUENTA CORRIENTE', 'COR');
