/* Sub Categorias */
INSERT INTO subcategories (description) VALUES ('ANTIVIBRADOR');
INSERT INTO subcategories (description) VALUES ('BANDAS');
INSERT INTO subcategories (description) VALUES ('BILLETERA');
INSERT INTO subcategories (description) VALUES ('BIVIDI');
INSERT INTO subcategories (description) VALUES ('BOLSA CUBRE MOCHILA');
INSERT INTO subcategories (description) VALUES ('BOLSO');
INSERT INTO subcategories (description) VALUES ('BOLSO DE GIMNASIA');
INSERT INTO subcategories (description) VALUES ('BUZO');
INSERT INTO subcategories (description) VALUES ('CALZA');
INSERT INTO subcategories (description) VALUES ('CAMISA');
INSERT INTO subcategories (description) VALUES ('CAMISETA');
INSERT INTO subcategories (description) VALUES ('CANGURO');
INSERT INTO subcategories (description) VALUES ('CANILLERA');
INSERT INTO subcategories (description) VALUES ('CARDIGAN');
INSERT INTO subcategories (description) VALUES ('CARTERA');
INSERT INTO subcategories (description) VALUES ('CASACA');
INSERT INTO subcategories (description) VALUES ('CASACA CON CAPUCHA');
INSERT INTO subcategories (description) VALUES ('CHALECO');
INSERT INTO subcategories (description) VALUES ('CHIMPUNERA');
INSERT INTO subcategories (description) VALUES ('CINTURON');
INSERT INTO subcategories (description) VALUES ('CONJUNTO SHORT POLO');
INSERT INTO subcategories (description) VALUES ('CORREA PORTA BOTELLA');
INSERT INTO subcategories (description) VALUES ('CUERDA');
INSERT INTO subcategories (description) VALUES ('FALDA');
INSERT INTO subcategories (description) VALUES ('GORRO');
INSERT INTO subcategories (description) VALUES ('GORRO DE NATACION');
INSERT INTO subcategories (description) VALUES ('GRIP');W
INSERT INTO subcategories (description) VALUES ('GUANTES');
INSERT INTO subcategories (description) VALUES ('GUANTES DE GYM');
INSERT INTO subcategories (description) VALUES ('GUANTES FOOTBALL');
INSERT INTO subcategories (description) VALUES ('INFLADOR');
INSERT INTO subcategories (description) VALUES ('LENTES');
INSERT INTO subcategories (description) VALUES ('LENTES DE NATACION');
INSERT INTO subcategories (description) VALUES ('MALETIN');
INSERT INTO subcategories (description) VALUES ('MALLA PARA PELOTA');
INSERT INTO subcategories (description) VALUES ('MEDIAS');
INSERT INTO subcategories (description) VALUES ('MOCHILA');
INSERT INTO subcategories (description) VALUES ('MONEDERO');
INSERT INTO subcategories (description) VALUES ('MORRAL');
INSERT INTO subcategories (description) VALUES ('MU�EQUERA');
INSERT INTO subcategories (description) VALUES ('OVERGRIP');
INSERT INTO subcategories (description) VALUES ('PANT 3/4');
INSERT INTO subcategories (description) VALUES ('PANTALON');
INSERT INTO subcategories (description) VALUES ('PELOTA');
INSERT INTO subcategories (description) VALUES ('PELOTA MINI');
INSERT INTO subcategories (description) VALUES ('PLANTILLAS');
INSERT INTO subcategories (description) VALUES ('POLO');
INSERT INTO subcategories (description) VALUES ('POLO CON CUELLO');
INSERT INTO subcategories (description) VALUES ('POLO MANGA LARGA');
INSERT INTO subcategories (description) VALUES ('POLO TECHFIT');
INSERT INTO subcategories (description) VALUES ('PORTA IPOD');
INSERT INTO subcategories (description) VALUES ('PORTA RAQUETA');
INSERT INTO subcategories (description) VALUES ('PORTADOR');
INSERT INTO subcategories (description) VALUES ('SANDALIA');
INSERT INTO subcategories (description) VALUES ('SENSORES');
INSERT INTO subcategories (description) VALUES ('SHORT');
INSERT INTO subcategories (description) VALUES ('SHORT DE SWIM');
INSERT INTO subcategories (description) VALUES ('SUDADERA');
INSERT INTO subcategories (description) VALUES ('TOMATODO');
INSERT INTO subcategories (description) VALUES ('TOP');
INSERT INTO subcategories (description) VALUES ('TOP ALTO');
INSERT INTO subcategories (description) VALUES ('TOP LARGO');
INSERT INTO subcategories (description) VALUES ('TRUZA DE BAÑO');
INSERT INTO subcategories (description) VALUES ('VISERA');
INSERT INTO subcategories (description) VALUES ('ZAPATILLA');