/* Usos */
INSERT INTO uses (description) VALUES ('FOOTBALL');
INSERT INTO uses (description) VALUES ('RUNNING');
INSERT INTO uses (description) VALUES ('TRAINING');
INSERT INTO uses (description) VALUES ('OUTDOOR');
INSERT INTO uses (description) VALUES ('RUNNING TRAIL');
INSERT INTO uses (description) VALUES ('ORIGINALS');
INSERT INTO uses (description) VALUES ('BASKETBALL');
INSERT INTO uses (description) VALUES ('URBANO');
INSERT INTO uses (description) VALUES ('CLASSIC');
INSERT INTO uses (description) VALUES ('TENNIS');
INSERT INTO uses (description) VALUES ('INDOOR');
INSERT INTO uses (description) VALUES ('SKATEBOARD');
INSERT INTO uses (description) VALUES ('TECHFIT');
INSERT INTO uses (description) VALUES ('SWIM');
INSERT INTO uses (description) VALUES ('CASUAL');
INSERT INTO uses (description) VALUES ('STUDIO');
INSERT INTO uses (description) VALUES ('WALKING');
INSERT INTO uses (description) VALUES ('DANCE');
INSERT INTO uses (description) VALUES ('FUTBOL');
INSERT INTO uses (description) VALUES ('REALFLEX');
INSERT INTO uses (description) VALUES ('TONING');
INSERT INTO uses (description) VALUES ('SKATEBOARDING');
INSERT INTO uses (description) VALUES ('DANCING');
INSERT INTO uses (description) VALUES ('NEO');
INSERT INTO uses (description) VALUES ('ACTION SPORTS');
INSERT INTO uses (description) VALUES ('SPORTSWEAR');
INSERT INTO uses (description) VALUES ('Weight training');
INSERT INTO uses (description) VALUES ('VOLLEYBALL');
INSERT INTO uses (description) VALUES ('YOGA');
INSERT INTO uses (description) VALUES ('VERANO');
INSERT INTO uses (description) VALUES ('LIFESTYLE');