/* EN VENTAS EL sale_point_id SI PUEDE SER NULO, PORQUE LAS VENTAS MANUALES NO NECESARIAMENTE SE REGISTRAN EN UN PUNTO DE VENTA */
ALTER TABLE sales ALTER COLUMN sale_point_id DROP NOT NULL;

/* EN VENTAS LA PERTENENCIA DE BOLETAS Y FACTURAS SE DEBE CONTROLAR CON LA SUCURSAL branch_id */
ALTER TABLE sales ADD COLUMN branch_id INTEGER;
ALTER TABLE sales ADD CONSTRAINT fk_sales_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id);