/* AGREGANDO DEPARTAMENTO, PROVINCIA, DISTRITO PARA DIRECCION DE SUCURSALES */
﻿ALTER TABLE branches ADD COLUMN department CHARACTER VARYING (250);
ALTER TABLE branches ADD COLUMN province CHARACTER VARYING (250);
ALTER TABLE branches ADD COLUMN district CHARACTER VARYING (250);

UPDATE branches SET department = 'TACNA', province = 'TACNA', district = 'TACNA';

ALTER TABLE branches ALTER COLUMN department SET NOT NULL;
ALTER TABLE branches ALTER COLUMN province SET NOT NULL;
ALTER TABLE branches ALTER COLUMN district SET NOT NULL;
