/* AGREGANDO PRECIO A LOS PRODUCTOS */
ALTER TABLE products ADD COLUMN price REAL NOT NULL DEFAULT 0.00

/* CREANDO LA TABLA SERIES */
CREATE TABLE series
(
  id serial NOT NULL,
  serie integer,
  "number" integer,
  CONSTRAINT pk_serie_id PRIMARY KEY (id)
);

/* RENOMBRANDO TABLA VOUCHERS A COUPONS */
ALTER TABLE vouchers RENAME TO coupons

/* CREANDO EL TIPO DE ESTADO */
CREATE TYPE STATE_TYPE AS ENUM ('DRAFT', 'DONE');
/* AGREGANDO EL ATRIBUTO ESTADO EN VENTAS */
ALTER TABLE sales ADD COLUMN state STATE_TYPE NOT NULL DEFAULT 'DRAFT';

/* AGREGANDO ATRIBUTO PARA DIFERENCIAR CUANDO UN REGISTRO DEBE CONSIDERARSE ELIMINADO O NO */
ALTER TABLE ages ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE banks ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE brands ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE categories ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE companies ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE coupons ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE credit_card ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE currencies ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE customers ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE depots ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE employees ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE measurements ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE purchase_orders ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE regime ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE sales ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE size ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE subcategories ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE suppliers ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE uses ADD COLUMN active BOOLEAN DEFAULT TRUE;
ALTER TABLE voucher_types ADD COLUMN active BOOLEAN DEFAULT TRUE;