/* AGREGANDO EL CAMPO total_cash_amount EN VENTAS PARA LLEVAR CUENTA DE LOS VUELTOS (CAMBIOS) */
ALTER TABLE sales ADD COLUMN total_cash_amount REAL NOT NULL DEFAULT 0;

/* INICIALMENTE CONSIDERAMOS QUE TODOS LOS CLIENTES PAGARON LO JUSTO (SIN VUELTO) */
UPDATE sales SET total_cash_amount = cash_amount;
