/* EN EL CASO DE FACTURAS O BOLETAS, SE DEBE DISCRIMINAR LAS SERIES POR SUCURSALES, YA QUE SIENDO DIFERENTES SUCURSALES SE PUEDE REPETIR LA SERIE */
ALTER TABLE series ADD COLUMN branch_id INTEGER;
ALTER TABLE series ADD CONSTRAINT fk_series_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id);

/* ESTA CONSULTA ES PARA ASIGNAR SUCURSALES A LAS SERIES DE BOLETAS O FACTURAS, QUE NO SEAN TICKETS O NOTAS DE CREDITO */
UPDATE series SET branch_id = 1 WHERE sale_point_id IS NULL;