ALTER TABLE companies ADD COLUMN company_name CHARACTER VARYING(100) NOT NULL DEFAULT '';
ALTER TABLE companies ADD COLUMN address CHARACTER VARYING(250) NOT NULL DEFAULT '';
ALTER TABLE companies ADD COLUMN department CHARACTER VARYING(250) NOT NULL DEFAULT 'TACNA';
ALTER TABLE companies ADD COLUMN province CHARACTER VARYING(250) NOT NULL DEFAULT 'TACNA';
ALTER TABLE companies ADD COLUMN district CHARACTER VARYING(250) NOT NULL DEFAULT 'TACNA';
ALTER TABLE companies ADD COLUMN ruc CHARACTER VARYING(11) NOT NULL DEFAULT '';

UPDATE companies SET company_name = 'LFA TACNA EIRL' WHERE id = 1;
UPDATE companies SET address = 'Pje. Vigil Nro 53' WHERE id = 1;
UPDATE companies SET ruc = '20532437548' WHERE id = 1;

UPDATE companies SET company_name = 'GAFCO SAC' WHERE id = 2;
UPDATE companies SET address = 'Av. Coronel Mendonza N° 1880' WHERE id = 2;
UPDATE companies SET ruc = '20302573086' WHERE id = 2;