/* AGREGANDO EL ATRIBUTO PARA ACCEDER A TODAS LAS SUCURSALES EN ROLES */
ALTER TABLE roles ADD COLUMN all_branches_granted BOOLEAN NOT NULL DEFAULT FALSE;

/* ESTABLECIENDO ACCESO A TODAS LAS SUCURSALES PARA EL ADMINISTRADOR */
UPDATE roles SET all_branches_granted = TRUE WHERE id = 1;
