/*AGREGAMNDO EMPRESA EN LA VENTA*/
ALTER TABLE sales ADD COLUMN company_id integer;

ALTER TABLE sales ADD CONSTRAINT "fk_sales_company_id" FOREIGN KEY (company_id)
REFERENCES companies (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;