/* Restando stock a producto 1242627-019 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1242627-019') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto 1242627-019 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1242627-019') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto 1242627-019 de talla L en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1242627-019') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 1;
/* Sumando stock a producto 1242627-019 de talla L en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1242627-019') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 2;
/* Restando stock a producto AJ9566 de talla NS en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 2, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AJ9566') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'NS')) AND branch_id = 1;
/* Sumando stock a producto AJ9566 de talla NS en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 2, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AJ9566') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'NS')) AND branch_id = 2;
/* Restando stock a producto 1257616-420 de talla S en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 1;
/* Sumando stock a producto 1257616-420 de talla S en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 2;
/* Restando stock a producto 1257616-420 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto 1257616-420 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto 1257616-420 de talla L en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 1;
/* Sumando stock a producto 1257616-420 de talla L en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1257616-420') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 2;
/* Restando stock a producto 1271719-410 de talla S en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271719-410') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 1;
/* Sumando stock a producto 1271719-410 de talla S en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271719-410') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 2;
/* Restando stock a producto 1271719-410 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271719-410') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto 1271719-410 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271719-410') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto AY1813 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AY1813') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto AY1813 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AY1813') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto AB7447 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AB7447') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto AB7447 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AB7447') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto AY3021 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AY3021') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto AY3021 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'AY3021') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto 1271851-428 de talla L en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271851-428') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 1;
/* Sumando stock a producto 1271851-428 de talla L en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1271851-428') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'L')) AND branch_id = 2;
/* Restando stock a producto S94596 de talla S en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'S94596') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 1;
/* Sumando stock a producto S94596 de talla S en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'S94596') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'S')) AND branch_id = 2;
/* Restando stock a producto S94596 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'S94596') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto S94596 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = 'S94596') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
/* Restando stock a producto 1239476-001 de talla M en Leguía */
UPDATE stock SET store_stock = GREATEST(store_stock - 1, 0) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1239476-001') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 1;
/* Sumando stock a producto 1239476-001 de talla M en Vigil */
UPDATE stock SET store_stock = GREATEST(store_stock, 0) + 1, last_entry = NOW(), first_entry = COALESCE(first_entry, NOW()) WHERE product_barcode_id = (SELECT id FROM product_barcodes WHERE product_detail_id = (SELECT id FROM product_details WHERE product_id = (SELECT id FROM products WHERE code = '1239476-001') AND company_id = 1) AND size_id = (SELECT id FROM size WHERE description = 'M')) AND branch_id = 2;
