UPDATE product_details SET price = '79.00', offer_price = '49.00', cost = '29.387', cost_currency = 'S', currency_cost = 'S', invoice_currency = 'D', invoice_cost = '7.79' WHERE product_id = (SELECT products.id FROM products WHERE products.code = '73722Z');
UPDATE product_details SET price = '69.00', offer_price = '39.00', cost = '22.527', cost_currency = 'S', currency_cost = 'S', invoice_currency = 'D', invoice_cost = '5.94' WHERE product_id = (SELECT products.id FROM products WHERE products.code = '73923Z');
UPDATE product_details SET price = '79.00', offer_price = '49.00', cost = '32.222', cost_currency = 'S', currency_cost = 'S', invoice_currency = 'D', invoice_cost = '8.56' WHERE product_id = (SELECT products.id FROM products WHERE products.code = '83021Z');

INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '28.232', 'S', 'S', 'D', '7.48', (SELECT products.id FROM products WHERE products.code = '73932Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '69.00', '39.00', '20.917', 'S', 'S', 'D', '5.51', (SELECT products.id FROM products WHERE products.code = '73953Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '69.00', '39.00', '20.392', 'S', 'S', 'D', '5.37', (SELECT products.id FROM products WHERE products.code = '73955Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '69.00', '39.00', '21.547', 'S', 'S', 'D', '5.68', (SELECT products.id FROM products WHERE products.code = '73925Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '69.00', '39.00', '20.917', 'S', 'S', 'D', '5.51', (SELECT products.id FROM products WHERE products.code = '73954Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '109.00', '79.00', '47.097', 'S', 'S', 'D', '12.57', (SELECT products.id FROM products WHERE products.code = '74531Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '27.217', 'S', 'S', 'D', '7.21', (SELECT products.id FROM products WHERE products.code = '83156Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '27.217', 'S', 'S', 'D', '7.21', (SELECT products.id FROM products WHERE products.code = '83161Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '27.217', 'S', 'S', 'D', '7.21', (SELECT products.id FROM products WHERE products.code = '83173Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '29.387', 'S', 'S', 'D', '7.79', (SELECT products.id FROM products WHERE products.code = '83176Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '69.00', '39.00', '22.527', 'S', 'S', 'D', '5.94', (SELECT products.id FROM products WHERE products.code = '83182Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '31.802', 'S', 'S', 'D', '8.44', (SELECT products.id FROM products WHERE products.code = '83194Z') );
INSERT INTO product_details (company_id, price, offer_price, cost, cost_currency, currency_cost, invoice_currency, invoice_cost, product_id) VALUES ( 1, '79.00', '49.00', '32.222', 'S', 'S', 'D', '8.56', (SELECT products.id FROM products WHERE products.code = '83227Z') );
