UPDATE stock SET store_stock = store_stock + 18, last_entry = NOW()::TIMESTAMP WITHOUT TIME ZONE WHERE branch_id = 1 AND product_barcode_id = ( 	SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73722Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7') );
UPDATE stock SET store_stock = store_stock + 12, last_entry = NOW()::TIMESTAMP WITHOUT TIME ZONE WHERE branch_id = 1 AND product_barcode_id = ( 	SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73923Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7') );
UPDATE stock SET store_stock = store_stock + 6, last_entry = NOW()::TIMESTAMP WITHOUT TIME ZONE WHERE branch_id = 1 AND product_barcode_id = ( 	SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83021Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7') );

INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73932Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 24, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73953Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73955Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '5')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73925Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '5')), 12, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '73954Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '74531Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 12, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83156Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 12, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83161Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 12, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83173Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83176Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83182Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 24, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83194Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 18, NOW()::TIMESTAMP WITHOUT TIME ZONE );
INSERT INTO stock (branch_id, product_barcode_id, store_stock, last_entry) VALUES ( 1, (SELECT product_barcodes.id FROM product_barcodes INNER JOIN 	product_details ON product_barcodes.product_detail_id = product_details.id INNER JOIN 	products ON product_details.product_id = products.id 	WHERE products.code = '83227Z' AND product_barcodes.size_id = (SELECT size.id FROM size WHERE size.description = '7')), 6, NOW()::TIMESTAMP WITHOUT TIME ZONE );
